# -*- coding: utf-8 -*-
"""OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzyvN0HQApZEtp1tganBovTZr0HkXakt
"""

!pip install opencv-python
!pip install matplotlib
!pip install numpy

!pip install torch==1.7.1+cpu torchvision==0.8.2+cpu torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
!pip install easyocr

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
import easyocr
import matplotlib.pyplot as plt
# %matplotlib inline

im_1_path = '/content/onl.jpg'

def recognize_text(img_path):
    '''loads an image and recognizes text.'''

    reader = easyocr.Reader(['en'])
    return reader.readtext(img_path)

result = recognize_text(im_1_path)

result

img_1 = cv2.imread(im_1_path)
img_1 = cv2.cvtColor(img_1, cv2.COLOR_BGR2RGB)
plt.imshow(img_1)

def overlay_ocr_text(img_path, save_name):
    '''loads an image, recognizes text, and overlays the text on the image.'''


    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    dpi = 80
    fig_width, fig_height = int(img.shape[0]/dpi), int(img.shape[1]/dpi)
    plt.figure()
    f, axarr = plt.subplots(1,2, figsize=(fig_width, fig_height))
    axarr[0].imshow(img)

    result = recognize_text(img_path)

    for (bbox, text, prob) in result:
        if prob >= 0.5:

            print(f'Detected text: {text} (Probability: {prob:.2f})')


            (top_left, top_right, bottom_right, bottom_left) = bbox
            top_left = (int(top_left[0]), int(top_left[1]))
            bottom_right = (int(bottom_right[0]), int(bottom_right[1]))

            cv2.rectangle(img=img, pt1=top_left, pt2=bottom_right, color=(255, 0, 0), thickness=10)


            cv2.putText(img=img, text=text, org=(top_left[0], top_left[1] - 10), fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 0, 0), thickness=8)


    axarr[1].imshow(img)
    plt.savefig(f'./output/{save_name}_onl.jpg', bbox_inches='tight')

overlay_ocr_text(im_1_path, 'onl')